defmodule InventoryLocatorWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :inventory_locator

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_inventory_locator_key",
    signing_salt: "H9aGb6RX",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :inventory_locator,
    gzip: not code_reloading?,
    only: InventoryLocatorWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Add security headers for user uploads to prevent XSS via uploaded files
  plug :secure_upload_headers

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :inventory_locator
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug InventoryLocatorWeb.Router

  @spec secure_upload_headers(Plug.Conn.t(), keyword()) :: Plug.Conn.t()
  defp secure_upload_headers(conn, _opts) do
    cond do
      String.starts_with?(conn.request_path, "/uploads/") ->
        conn
        |> Plug.Conn.put_resp_header("content-disposition", "inline")
        |> Plug.Conn.put_resp_header("x-content-type-options", "nosniff")

      String.starts_with?(conn.request_path, "/documents/") ->
        conn
        |> Plug.Conn.put_resp_header("content-disposition", "inline")
        |> Plug.Conn.put_resp_header("x-content-type-options", "nosniff")

      true ->
        conn
    end
  end

  @spec check_origin(URI.t()) :: boolean()
  def check_origin(%URI{host: host}) do
    cond do
      host in ["localhost", "127.0.0.1"] -> true
      String.ends_with?(host, ".local") -> true
      private_ip?(host) -> true
      true -> false
    end
  end

  @spec private_ip?(String.t()) :: boolean()
  defp private_ip?(host) do
    case :inet.parse_address(String.to_charlist(host)) do
      {:ok, {192, 168, _, _}} -> true
      {:ok, {10, _, _, _}} -> true
      {:ok, {172, b, _, _}} when b >= 16 and b <= 31 -> true
      _ -> false
    end
  end
end
